### ISSUE TITLE
Remove backend requirement?

### ISSUE THREAD

**Issue by dbushong** [decorator-factory/pyright-playground#5]
Hello; great site!  Super helpful for sharing python typing examples with friends.

Out of curiosity, is there any reason this needs the NodeJS backend?  Could the pyright engine be built with webpack and run in the browser?  You could set aggressive cache headers on the frontend JS/HTML, and your server costs would drop to near-zero.  :-)

**Comment by decorator-factory** [comment]
Hello!

There's https://github.com/Zzzen/pyright-ast-viewer, which does exactly that

I honestly just never looked into the possibility, and I didn't bother implementing it because there's already pyright-ast-viewer.

**Comment by dbushong** [comment]
Neat; thanks!
