### ISSUE TITLE
Certificate expired on pyright playground site

### ISSUE THREAD

**Issue by erictraut** [decorator-factory/pyright-playground#6]
It looks like the SSL certificate has expired, so accessing the pyright playground results in a scary message from the browser.

**Comment by decorator-factory** [comment]
Yeah I know, there's some issue with my cloud provider and I'm a bit too busy to resolve it right now :(

in the meantime there's this: https://github.com/Zzzen/pyright-ast-viewer which seems much cooler in general

**Comment by decorator-factory** [comment]
Actually I just fixed it :+1:

**Comment by erictraut** [comment]
Awesome! Thanks.
